### ISSUE TITLE
Just not working

### ISSUE THREAD

**Issue by jeremycherfas** [finanalyst/grav-plugin-map-marker-leaflet#1]
Hi. I was very keen to try this out mapping the data I get from trails.io on my phone. The data export is way more complex than your example (I can provide an example) so I cut it right down to lat and lng. Actually lng lat, because that's the order in which they are supplied, buyt that shouldn't make much difference. Anyway, I created a page like your example, and then realised that there doesn't seem to be any provision to give `"type":"LineString"` to indicate that I wanted a route rather than a series of markers.

I then made a page that is an exact copy of your example, but instead of a map, I just saw the code displayed on the page.

My absolute ideal would be to upload the geoJSON file I receive to the server and have that displayed, probably with a different template. The file looks like this:

````
{"type":"FeatureCollection","properties":{"tags":[],"title":"Early morning nordic walk","creator":{"name":"Trails","version":"4.06"},"trackId":"3901229952366592057"},"features":[{ "type": "Feature", "properties": {"time":"2018-09-14T05:38:27Z", "summaryStatistics": {"AltitudeAverage": 69.896367, "SpeedAvg": 1.757111, "PaceAverage": 0.569116, "Distance": 4339.355604, "Duration": 2469.597126, "DurationWhileMoving": 2437.991642, "SpeedAvgWhileMoving": 1.779569, "StepCountCumulated": 4683.000000, "StepCountPerMinuteAverage": 114.032754, "Ascent": 52.506265, "Descent": 56.314415}, "timeline":[{"elevation": 82.153042,"course": -1.000000,"speed": 0.000000,"time": 1536903507.006996,"cumulatedDistance": 0.000000,"coordinate":[ 12.458597, 41.887436, 82.153042 ]}
````

And then a lot more elements in timeline until a section of geometry, which repeats lng, lat and elevation:

````
"geometry":{"coordinates":[[ 12.458597, 41.887436, 82.153042 ],[ 12.458542, 41.887405, 83.039211 ],
````

Etc, finally ending with "type":"LineString"}

I'm not sure how possible that is as I have only just started to think about working with leaflet.js and my tracks, but I'm happy to test things if need be.

**Comment by jeremycherfas** [comment]
I dug in further and, probably because I am new to mapping, some things appear to be missing. For example, the CSS and script that https://leafletjs.com/examples/quick-start/ says are necessary do not appear in the `<head>`. I tried inserting them there myself, but it made no difference.

I also looked to see how the temples/partials/*.html.twig were getting into the page, and they did not appear to be. I tried making a new template to include these, but again it made no difference.

I realise I may not be very effective at this, and I very much appreciate your plugins. I do have the feeling that I need more explanation and, possibly, example templates.

May I ask, what theme are you using? And would you be willing to share your templates, or extend the readme.md to include more details.

**Comment by finanalyst** [comment]
Sorry for delay. I'm in Hong Kong and we were just hit by a super typhoon,
or hurricane cat 5. Still raining as I write.

I wrote the plugin to handle a hiking task. You can see it at mgc.1ptd.com

If you select my name in hiker table, Richard Hainsworth, and press select
hiker, you will see my peaks.

What you are wanting is a set of point markers. Im not sure how that is
done. I use a GPS tracking app called locux maps, and that uses
openstreetmap data without a map style provider. It also does lines (try
their map planning function). But that seems to use another library.

So what it seems to me that you are asking is for is more than markers. But
I didn't include that sort of functionality in my plugin.

Have you managed to get a map with the plugin?

Next get a marker on the map.

The JavaScript and CSS for leaflet are included using this plug-in. They
are downloaded from a CDN. This happens in the short code function see the
PHP programs in the shortcodes directory.

The js and CSS for the markers are also called in the mapleaflet sortcode
PHP because they have to be called after the leaflet js. But they are in
the assets directory because I modified them.

The test file in the readme is set up using a standard Grav with Quark
theme.

By the way, when you say the js is not in Head, how did you test this? Grav
should be putting them there. Have you looked to see whether there is a
failure message in the js console in the browser? I use Firefox, which has
a web developer tab.

Regards.

**Comment by jeremycherfas** [comment]
Many thanks. In the end the plugin was an inspiration to get into attempting to do it myself without shortcodes. I've succeeded in a rudimentary way and will be writing up in a day or two.
