### ISSUE TITLE
Colors, icons and popups are not working anymore

### ISSUE THREAD

**Issue by faebut** [finanalyst/grav-plugin-map-marker-leaflet#19]
I used this plugin for the past few months without any problems. Now there seem to be some issues: I can't get any colors apart from the basic ones like blue, red, green, white and so on, to work. As soon as I try something like cadetblue, salmon or darkgreen, the marker turns red. 

this used to work:
`[map-leaflet lat=47.395 lng=8.039 zoom=16 mapname=neighbourhood style=neighbourhood scale]
[a-markers markerColor="cadetblue" iconColor="white"]
[{ "lat": 47.3962, "lng":8.03759, "icon": "robot", "title": "Prozessor" }]
[/a-markers]
[/map-leaflet]`
But now the marker is red and there's no icon. The popup appears somewhere on the map but not close to the marker. I'm not sure if the last one used to work or was styled differently. 

I also tested the examples in the readme. They had the same issues.

**Comment by finanalyst** [comment]
@faebut  Sorry to be so slow. I just discovered a lot of things in spam. The change occurred because I updated the plugin to allow for more providers. Also a different set of markers is now possible. Let me see if I can add new colours with the new markers.
If you prefer the previous version, there is a possibility to go back to a previous version of the plugin.

**Comment by finanalyst** [comment]
The change is due to a shift to Extra-Marker leaflet plugin. I have put documenting this on the Todo list.
