### ISSUE TITLE
Leaflet parameters

### ISSUE THREAD

**Issue by timothyarmes** [finanalyst/grav-plugin-map-marker-leaflet#4]
Could you please allow us to pass leaflet  map creation parameters such as `scrollWheelZoom`. Currently we need to modify the plugin to do this.

**Comment by traumturbulenzen** [comment]
I wish that too. It would be just as nice that spaces are possible in the title parameter.

**Comment by finanalyst** [comment]
@timothyarmes Very sorry to have been so slow. I don't have notifications set up.

I have not included much of the functionality since I didn't know whether the plugin would be generally useful.

If you have already got a work around, please send me a Pull Request with the changes, and I will look to see how to include it.

**Comment by finanalyst** [comment]
@traumturbulenzen The problem with spaces in the title is a difficulty inside the Leaflet plugin, not in this plugin that exposes Leaflet to Grav. (I think!)

If I am wrong and there is a workaround, please let me know. The best I can suggest is to use '_' (underscore) which is a common way of showing a space. Also, I think that using non-breaking space may work, but you might have to play around to get a `&nbsp;` into the text string.

**Comment by finanalyst** [comment]
@timothyarmes Thanks for the improvement suggested for Thunderforest. I have implemented it and added you to the credits of the README
Please let me know about including more functionality. I will try to be a bit more proactive. (looking into how to get notifications of issues by email)
