### ISSUE TITLE
Using markers from other pages

### ISSUE THREAD

**Issue by iainhallam** [finanalyst/grav-plugin-map-marker-leaflet#5]
I'm wondering whether it would be possible to add a way to use markers from other pages, perhaps in a taxonomy category? That way, you could include custom fields to define the latitude and longitude for a page, and then show them all on a single map on another page.

**Comment by finanalyst** [comment]
Sorry for the delay. It is not easy to use other markers - unfortunately. If you look at the code, you will see that all of the markers are contained in a single image and then shown by css 'boxing'. This is a very efficient mechanism because the image is sent by the server to the client only once, but the client can then use it any number of times. If (like I did) you want a 100 markers, then the payload from the server to the client would be quite large, but by using a single image, 1 marker or 100 markers makes no difference.

It is however possible to associate (short) text with a marker and have it pop up on hover (for a PC, doesn't work well with a mobile). 

Otherwise, I do not quite understand what you are trying to do. What do you mean markers from other pages?

**Comment by iainhallam** [comment]
I just wanted to be able to show a map on one page whose points of interest were the locations of other pages. The use case is to make a directory of locations, where each location has a single page about it, and then show a map summarising where those locations are.
